function advice = getOwnerAdvice(predictedDisease)
% Returns a cell array of advice lines for the given disease label.

d = char(predictedDisease);  % ensure char for switch

switch d

    case 'Actinic Keratosis'
        advice = {
            'ACTINIC KERATOSIS  (Risk: Moderate–High)'
            '--------------------------------------------------'
            'Overview:'
            'A sun-induced precancerous skin condition that'
            'can progress into squamous cell carcinoma if untreated.'
            ''
            'What you may notice:'
            '- Rough, dry or scaly skin patches'
            '- Red or inflamed skin'
            '- Hair loss over the lesion'
            ''
            'Immediate precautions:'
            '- Reduce sun exposure (especially 10 AM – 4 PM)'
            '- Keep the dog in shaded or indoor areas'
            '- Do NOT apply human creams, Dettol, or home remedies'
            ''
            'Diet & care:'
            '- Provide a balanced diet with omega-3 fatty acids'
            '- Ensure constant access to clean water'
            ''
            'When to see a vet:'
            '- If the lesion is bleeding, growing, or changing color'
            '- If the dog is repeatedly licking or scratching the area'
            ''
            'Disclaimer: This tool is a screening aid, not a final diagnosis.'
            'Always consult a licensed veterinarian for confirmation and treatment.'
        };

    case 'Melanoma'
        advice = {
            'MELANOMA  (Risk: High – Potentially Life-Threatening)'
            '--------------------------------------------------'
            'Overview:'
            'A serious form of skin cancer that can spread to'
            'internal organs if not treated promptly.'
            ''
            'What you may notice:'
            '- Dark black or brown skin growths'
            '- Bleeding or ulcerated lumps'
            '- Rapid growth in size or shape'
            ''
            'Immediate actions (URGENT):'
            '- Arrange an immediate veterinary visit'
            '- Prevent the dog from scratching or biting the lesion'
            '- Do NOT squeeze or puncture the lesion'
            ''
            'Diet & support (not a cure):'
            '- High-quality, easily digestible food'
            '- Vet-approved supplements only'
            ''
            'When to see a vet:'
            '- ALWAYS – melanoma is an emergency condition'
            ''
            'Disclaimer: This tool is a screening aid, not a final diagnosis.'
            'Early veterinary intervention is critical for the best outcome.'
        };

    case 'Seborrheic Keratosis'
        advice = {
            'SEBORRHEIC KERATOSIS  (Risk: Low – Usually Benign)'
            '--------------------------------------------------'
            'Overview:'
            'A non-cancerous, wart-like skin growth commonly'
            'seen in older dogs.'
            ''
            'What you may notice:'
            '- Small, raised, wart-like or crusty lesions'
            '- Usually not painful'
            '- Mild itching in some cases'
            ''
            'Home care:'
            '- Keep the area clean and dry'
            '- Use mild, vet-recommended shampoos if advised'
            '- Prevent excessive scratching or chewing'
            ''
            'What to avoid:'
            '- Do not cut, squeeze, or pull the growth'
            '- Avoid harsh chemical sprays or human ointments'
            ''
            'When to see a vet:'
            '- If the growth changes size or color suddenly'
            '- If there is bleeding, infection, or foul smell'
            ''
            'Disclaimer: This condition is generally benign, but'
            'any change should be evaluated by a veterinarian.'
        };

    case 'Vascular Lesion'
        advice = {
            'VASCULAR LESION  (Risk: Variable – Needs Evaluation)'
            '--------------------------------------------------'
            'Overview:'
            'Lesions arising from blood vessels, which can be'
            'benign (e.g., hemangioma) or more serious.'
            ''
            'What you may notice:'
            '- Red, purple, or dark lesions on the skin'
            '- Swelling or soft lumps'
            '- Occasional bleeding'
            ''
            'Immediate precautions:'
            '- Avoid trauma or pressure on the lesion'
            '- If bleeding, apply gentle pressure with clean gauze'
            '- Prevent the dog from licking or biting the area'
            ''
            'Diet & care:'
            '- Maintain a balanced, vet-approved diet'
            '- Ensure hydration and general health support'
            ''
            'When to see a vet:'
            '- If bleeding is frequent or does not stop'
            '- If the lesion suddenly enlarges or darkens'
            '- For proper diagnosis (e.g., biopsy, imaging)'
            ''
            'Disclaimer: Only a veterinarian can distinguish benign'
            'from malignant vascular lesions. This tool is a guide only.'
        };

    otherwise
        advice = {
            'UNSPECIFIED SKIN LESION'
            '--------------------------------------------------'
            'The system could not match this lesion to a specific'
            'trained disease category with full confidence.'
            ''
            'General precautions:'
            '- Do not apply human medications or home remedies'
            '- Prevent constant licking, biting, or scratching'
            '- Keep the area clean and dry'
            ''
            'Please consult a licensed veterinarian for a thorough'
            'examination, accurate diagnosis, and treatment plan.'
        };

end

end
